### ISSUE TITLE
Accessing admin

### ISSUE THREAD

**Issue by mhn-mnsr** [rajujha373/portfolio#7]
How do I gain access to login? I really like your layout and wanted to make use of it for my own portfolio. Please help with this.

**Comment by irkartik** [comment]
Glad you liked it @mhn-mnsr , in order to access the admin panel you need to create credentials for it first. You can do it by the following command ::

    $ python manage.py createsuperuser 

Enter the username and password you want to create and then finally login to the admin panel via {your-url-link}/admin ... assuming you're running on local machine on port 8000, your admin panel opens up at localhost:8000/admin

**Comment by mhn-mnsr** [comment]
Awesome! Thanks for you quick response! I have a few additional questions regarding the project, I'm quite new to web development, and have a few loose-ends. Do you mind sharing your email address with me? Or drop me an email at: mhn1211@gmail.com :)

**Comment by irkartik** [comment]
you can contact me at rajujha373@gmail.com or my gitter handle is rajujha373
